stages:
- greeting
- build
- run

hello world:
  stage: greeting
  script:
   - echo "Hey there! Let's do some physics."

build_image:
  stage: build
  variables:
    TO: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  tags:
    - docker-image-build
  script:
    - ignore

make_met:
  stage: run
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  script:
    - python processor/minimal.py
  artifacts:
    paths:
      - /tmp_plots/MET_pt_shape.pdf
    expire_in: 1 week
